export default function TargetsDummy() {
    return [
        {
            uuid: "1dsf23r2",
            level: "commission",
            type: "internal",
            title: "Digital Transformation Initiative",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            category: "IT",
            group_division: "Information Systems Division",
            functional_group: "MSSG",
            status: "ongoing",
            start_date: "2024-02-01",
            end_date: "2024-04-30",
            progress: 50,
            last_update: "2024-02-15",
            banner: true
        },
        {
            uuid: "2w3refds",
            level: "commission",
            type: "external",
            title: "Cybersecurity Assessment",
            description: "Conduct a comprehensive assessment of cybersecurity measures to identify vulnerabilities and enhance security protocols.",
            category: "Security",
            group_division: "Information Systems Division",
            functional_group: "MSSG",
            status: "pending",
            start_date: "2024-03-15",
            end_date: "2024-04-15",
            progress: 10,
            last_update: "2024-03-01",
            banner: false
        },
        {
            uuid: "asdsf324",
            level: "commission",
            type: "internal",
            title: "Employee Training Program",
            description: "Develop and implement a comprehensive training program for government employees to enhance skills and competencies.",
            category: "Human Resources",
            group_division: "HR Division",
            functional_group: "MSSG",
            status: "completed",
            start_date: "2023-12-01",
            end_date: "2024-02-28",
            progress: 100,
            last_update: "2024-03-05",
            banner: true
        },
        {
            uuid: "sadf23re",
            level: "commission",
            type: "external",
            title: "Regulatory Compliance Audit",
            description: "Conduct an audit to ensure compliance with regulatory requirements and standards.",
            category: "Compliance",
            group_division: "Licensing Division",
            functional_group: "MSSG",
            status: "onhold",
            start_date: "2024-01-15",
            end_date: "2024-03-15",
            progress: 30,
            last_update: "2024-02-10",
            banner: false
        },
        {
            uuid: "3f3d2gh4",
            level: "comission",
            type: "internal",
            title: "E-Government Services Enhancement",
            description: "Upgrade and modernize government services to improve accessibility and efficiency for citizens.",
            category: "Maintenance",
            group_division: "Information Systems Division",
            functional_group: "MSSG",
            status: "ongoing",
            start_date: "2024-01-01",
            end_date: "2024-06-30",
            progress: 40,
            last_update: "2024-02-20",
            banner: true
        },
        {
            uuid: "4swr35f6",
            level: "commission",
            type: "internal",
            title: "Government Employee Wellness Program",
            description: "Implement a wellness program to promote the health and well-being of government employees.",
            category: "Human Resources",
            group_division: "HR Division",
            functional_group: "MSSG",
            status: "ongoing",
            start_date: "2024-01-01",
            end_date: "2024-12-31",
            progress: 20,
            last_update: "2024-02-15",
            banner: true
        },
        {
            uuid: "3rewx94a",
            level: "commission",
            type: "internal",
            title: "Government Transparency Initiative",
            description: "Enhance transparency and accountability in government operations through improved data disclosure and public access.",
            category: "Governance",
            group_division: "Governance Division",
            functional_group: "Transparency Team",
            status: "ongoing",
            start_date: "2024-04-01",
            end_date: "2024-12-31",
            progress: 0,
            last_update: "2024-02-20",
            banner: true
        },
    ]
}
